# Generated by Django 6.0.7 on 2026-08-08 03:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guantou", "0004_api_v1_domain_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="flavorpackage",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="创建时间",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="package",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="flavorpackage",
            name="flavor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="guantou.flavor",
                verbose_name="风味",
            ),
        ),
        migrations.AlterField(
            model_name="flavorpackage",
            name="package",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="guantou.package",
                verbose_name="包装",
            ),
        ),
    ]
