# Generated by Django 6.1 on 2026-08-27 08:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guantou", "0018_can_transition_log_to_relations"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="cancomment",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="guantou.cancomment",
                verbose_name="回复目标",
            ),
        ),
        migrations.AddField(
            model_name="cancomment",
            name="reply_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="comment_replies_received",
                to=settings.AUTH_USER_MODEL,
                verbose_name="回复对象",
            ),
        ),
        migrations.AddIndex(
            model_name="cancomment",
            index=models.Index(
                fields=["parent", "created_at"], name="guantou_can_parent__9f8f8b_idx"
            ),
        ),
    ]
